//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWH.DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AppEntities : DbContext
    {
        public AppEntities()
            : base("name=AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questionnaire> Questionnaire { get; set; }
        public virtual DbSet<ActiveInfo> ActiveInfo { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<QuestionnaireResultList_Result> QuestionnaireResultList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuestionnaireResultList_Result>("QuestionnaireResultList");
        }
    
        public virtual ObjectResult<QuestionResultList_Result> QuestionResultList(Nullable<int> qusId, Nullable<int> deptId)
        {
            var qusIdParameter = qusId.HasValue ?
                new ObjectParameter("qusId", qusId) :
                new ObjectParameter("qusId", typeof(int));
    
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuestionResultList_Result>("QuestionResultList", qusIdParameter, deptIdParameter);
        }
    
        public virtual ObjectResult<UserResultList_Result> UserResultList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserResultList_Result>("UserResultList");
        }
    
        public virtual int Active_Nh_Delete(Nullable<int> userId, Nullable<int> groupId, ObjectParameter result)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Active_Nh_Delete", userIdParameter, groupIdParameter, result);
        }
    
        public virtual int Active_Nh_Insert(Nullable<int> userId, Nullable<int> parentId, string userName, string sex, string isChild, Nullable<int> groupId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("parentId", parentId) :
                new ObjectParameter("parentId", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var isChildParameter = isChild != null ?
                new ObjectParameter("isChild", isChild) :
                new ObjectParameter("isChild", typeof(string));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Active_Nh_Insert", userIdParameter, parentIdParameter, userNameParameter, sexParameter, isChildParameter, groupIdParameter);
        }
    }
}
