//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWH.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userId { get; set; }
        public int deptId { get; set; }
        public string userCode { get; set; }
        public string userName { get; set; }
        public int parentId { get; set; }
        public string sex { get; set; }
        public bool isChild { get; set; }
        public string relative { get; set; }
        public string relativePhone { get; set; }
        public string remark { get; set; }
    }
}
